name: Auto-update events.json

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:        # Allow manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history for reliable rebase
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
    
    - name: Fetch and build events
      run: python fetch_and_build.py
    
    - name: Commit and push updated feed
      run: |
        git config --global user.name  "github-actions[bot]"
        git config --global user.email "actions@github.com"

        git add events.json
        if git diff --cached --quiet; then
          echo "No changes to commit"
          exit 0
        fi

        git commit -m "CI: update events.json"
        git fetch origin main
        git pull --rebase origin main || true
        git push origin HEAD:main

