- uses: actions/setup-python@v5
  with:
    python-version: '3.11'
    cache: 'pip'

- name: Install deps
  run: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt

- name: Build
  run: |
    python fetch_and_build.py --debug --allow-empty
