name: Build events.json

on:
  workflow_dispatch:
  schedule:
    - cron: '17 * * * *'  # run hourly at :17

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build events.json
        run: |
          python fetch_and_build.py --allow-empty --debug
          ls -lh events.json
          sed -n '1,40p' tmp_lnsb/preview.txt || true

      - name: Upload artifacts (events + debug)
        uses: actions/upload-artifact@v4
        with:
          name: svb-events
          path: |
            events.json
            tmp_lnsb/**
